spring.application.name=backend
spring.datasource.url=jdbc:mysql://matthewmoyer.cikeys.com:3306/matthewm_food_health?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=matthewm_testuser
spring.datasource.password=Mbmcipw2!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true